language: node_js
node_js:
  - node

dist: bionic
sudo: required

branches:
  only:
   - master

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod --base-href https://crazy-hour-ai.github.io/my-weather-app/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/my-day06-service
  on:
    branch: master